menu:
  # Home: /
  首页: /
  # Archives: /archives
  归档: /archives
  # About: /about
  关于: /about
rss: /atom.xml

excerpt_link: Read More #摘要链接文字
archive_yearly: false #按年存档

widgets: #配置页脚显示哪些小挂件
  - category
#  - tag
  - tagcloud
  - recent_posts
#  - blogroll

archive_date_format: MMM DD
fancybox: true

duoshuo_shortname: driftingwind

google_analytics:
favicon: /favicon.ico

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_comment: '坚持分享，您的支持将鼓励我继续创作！'
# 打赏wording
reward_wording: '谢谢打赏'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /images/ALiPay.jpg
# 微信二维码图片地址
weixin: /images/WeChatPay.jpg
