menu:
  # Home: /
  首页: /
  # Archives: /archives
  归档: /archives
  # About: /about
  关于: /about
rss: /atom.xml

excerpt_link: Read More #摘要链接文字
archive_yearly: false #按年存档

widgets: #配置页脚显示哪些小挂件
  - category
#  - tag
  - tagcloud
  - recent_posts
#  - blogroll

archive_date_format: MMM DD
fancybox: true

duoshuo_shortname: driftingwind

google_analytics:
favicon: /favicon.ico
